import Head from "next/head";
import React from "react";

const HeadComponent = ({ pageName }: { pageName: string }) => {
  return (
    <Head>
      <title>Advanced Devs | {pageName}</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default HeadComponent;
